"""Helpers for running karpathy/autoresearch on Modal."""

from .core import (
    RESULTS_HEADER,
    SEEDED_REPO_RUNTIME_ARTIFACTS,
    VENDORED_PROJECT_ROOT_ENTRIES,
    AutoresearchPaths,
    TrainingSummary,
    append_result_row,
    branch_name,
    build_autoresearch_agent_prompt,
    build_claude_baseline_prompt,
    build_paths,
    copy_vendored_project_root,
    ensure_results_file,
    generate_run_tag,
    is_data_ready,
    parse_training_summary,
    resolve_run_tag,
    validate_run_tag,
)

__all__ = [
    "RESULTS_HEADER",
    "AutoresearchPaths",
    "SEEDED_REPO_RUNTIME_ARTIFACTS",
    "TrainingSummary",
    "VENDORED_PROJECT_ROOT_ENTRIES",
    "append_result_row",
    "build_autoresearch_agent_prompt",
    "branch_name",
    "build_claude_baseline_prompt",
    "build_paths",
    "copy_vendored_project_root",
    "ensure_results_file",
    "generate_run_tag",
    "is_data_ready",
    "parse_training_summary",
    "resolve_run_tag",
    "validate_run_tag",
]
